In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df1=pd.read_csv("gdp.csv",encoding='latin-1')
df1.head()

,Country,Subject Descriptor,Units,Scale,2015,Estimates Start After
0,Afghanistan,"Gross domestic product per capita, current prices",U.S. dollars,Units,599.994,2013.0
1,Albania,"Gross domestic product per capita, current prices",U.S. dollars,Units,"3,995.38",2010.0
2,Algeria,"Gross domestic product per capita, current prices",U.S. dollars,Units,"4,318.14",2014.0
3,Angola,"Gross domestic product per capita, current prices",U.S. dollars,Units,"4,100.32",2014.0
4,Antigua and Barbuda,"Gross domestic product per capita, current prices",U.S. dollars,Units,"14,414.30",2011.0

In [9]:
df1_refined=pd.read_csv("gdp.csv",usecols=['Country','2015'],encoding='latin-1')
df1_refined.head()

               Country       2015
0          Afghanistan    599.994
1              Albania   3,995.38
2              Algeria   4,318.14
3               Angola   4,100.32
4  Antigua and Barbuda  14,414.30

In [13]:
df1_refined=df1_refined.rename(columns={'2015':'GDP'})
df1_refined.head()

               Country        GDP
0          Afghanistan    599.994
1              Albania   3,995.38
2              Algeria   4,318.14
3               Angola   4,100.32
4  Antigua and Barbuda  14,414.30

In [15]:
df2=pd.read_csv("satisfaction.csv",encoding='latin-1')
df2.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [53]:
df2_refined=pd.read_csv("satisfaction.csv",usecols=['Country or region','Score'],encoding='latin-1')
df2_refined=df2_refined.rename(columns={'Country or region':'Country'})

In [67]:
df2_refined = df2_refined.sort_values(by=['Country'], ascending=True)
df2_refined.head()

         Country  Score
153  Afghanistan  3.203
106      Albania  4.719
87       Algeria  5.211
46     Argentina  6.086
115      Armenia  4.559

In [68]:
merged_df = pd.merge(df1_refined, df2_refined, on='Country')

In [69]:
df_merged.head(150)

                 Country        GDP  Score
0            Afghanistan    599.994    NaN
1                Albania   3,995.38    NaN
2                Algeria   4,318.14    NaN
3                 Angola   4,100.32    NaN
4    Antigua and Barbuda  14,414.30    NaN
..                   ...        ...    ...
145           Seychelles  14,940.71    NaN
146         Sierra Leone    659.438    NaN
147            Singapore  52,887.77    NaN
148      Slovak Republic  15,991.74    NaN
149             Slovenia  20,732.48    NaN

[150 rows x 3 columns]

In [70]:
frame=[df1_refined,df2_refined]
result=pd.concat(frame)
result.head(160)

                            Country        GDP  Score
0                       Afghanistan    599.994    NaN
1                           Albania   3,995.38    NaN
2                           Algeria   4,318.14    NaN
3                            Angola   4,100.32    NaN
4               Antigua and Barbuda  14,414.30    NaN
..                              ...        ...    ...
155             St. Kitts and Nevis  16,109.71    NaN
156                       St. Lucia   8,191.98    NaN
157  St. Vincent and the Grenadines   6,882.29    NaN
158                           Sudan   2,175.40    NaN
159                        Suriname   9,305.69    NaN

[160 rows x 3 columns]