In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sam=pd.read_csv("sample_submission.csv")

In [3]:
test=pd.read_csv("social_test.txt")

In [5]:
test.shape

(8959, 2)

In [6]:
sam.shape

(8959, 3)

In [8]:
sam.head()

    776731  264324  0.326395191186
0   666155   95308        0.896051
1   535123  755942        0.334125
2   786734  712538        0.177526
3  1064729    3905        0.415415
4   486287  372384        0.981808

In [9]:
test.head()

    776731  264324
0   666155   95308
1   535123  755942
2   786734  712538
3  1064729    3905
4   486287  372384