In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data=pd.read_csv("data.csv",encoding='latin')

In [6]:
data.head()

,Year,Country,Region,Song language,Artist,Song,English translation,Artist gender,Group/Solo,Place,...,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74
0,2010.0,Moldova,Former Socialist Bloc,English,SunStroke Project and Olia Tira,"""Run Away""",?,Both,Group,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010.0,Russia,Former Socialist Bloc,English,Peter Nalitch Band,"""Lost and Forgotten""",?,Male,Group,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010.0,Estonia,Former Socialist Bloc,English,Malcolm Lincoln and Manpower 4,"""Siren""",?,Male,Group,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010.0,Slovakia,Former Socialist Bloc,Slovak,Kristina,"""Horehronie""",Horehronie,Female,Solo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010.0,Finland,Scandinavia,Finnish,Kuunkuiskaajat,"""Tylki ell""","One can work for a living, too",Female,Group,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data.describe()

,Year,Place,Points,Approximate Betting Prices,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,...,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74
count,39.0,0.0,0.0,39.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2010.0,NaN,NaN,89.410256,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.0,NaN,NaN,71.916149,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2010.0,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2010.0,NaN,NaN,34.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2010.0,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2010.0,NaN,NaN,126.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2010.0,NaN,NaN,260.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data.isna().sum()

Year             38
Country          38
Region           38
Song language    38
Artist           38
                 ..
Unnamed: 70      77
Unnamed: 71      77
Unnamed: 72      77
Unnamed: 73      77
Unnamed: 74      77
Length: 75, dtype: int64

In [10]:
final_data=pd.read_csv("Final data by year.csv",encoding='latin1')
final_data

,Year,Country,Region,Song language,Artist,Song,English translation,Artist gender,Group/Solo,Place,...,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74
0,2009,Lithuania,Former Socialist Bloc,"English, Russian",Sasha Son,"""Love""",?,Male,Solo,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2009,Israel,Independent,"English, Hebrew, Arabic",Noa and Mira Awad,"""There Must Be Another Way""",?,Female,Group,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,France,Western Europe,French,Patricia Kaas,"""Et s'il fallait le faire""",And if it had to be done,Female,Solo,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2009,Sweden,Scandinavia,"English, French",Malena Ernman,"""La voix""",The voice,Female,Solo,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2009,Croatia,Former Yugoslavia,Croatian,Igor Cukrov feat. Andrea,"""Lijepa Tena""",Beautiful Tena,Both,Group,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,1998,Finland,Independent,Finnish,Edea,"""Aava""",Open landscape,NaN,NaN,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,1998,Norway,Scandinavia,Norwegian,Lars Fredriksen,"""Alltid sommer""",Always summer,NaN,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,1998,Estonia,Former Socialist Bloc,Estonian,Koit Toome,"""Mere lapsed""",Children of the sea,NaN,NaN,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,1998,Turkey,Independent,Turkish,Tzmen,"""UnutamazsÕn""",You can't forget,NaN,NaN,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,1998,Macedonia,Former Yugoslavia,Macedonian,Vlado Janevski,"""Ne zori, zoro""","Dawn, don't rise",NaN,NaN,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
final_data.isna().sum()

Year               0
Country            0
Region             0
Song language      0
Artist             0
                ...
Unnamed: 70      291
Unnamed: 71      291
Unnamed: 72      291
Unnamed: 73      291
Unnamed: 74      291
Length: 75, dtype: int64